// react/src/components/Button/index.js
import React from 'react'
import PropTypes from 'prop-types'
import styled from 'styled-components'
import is from 'styled-is'
import themes from './themes'

export const ButtonBase = styled.button`
  width: 100%;
  text-align: center;
  padding: 0;
  border-radius: 3px;
  margin-bottom: 8px;
  height: 60px;
  outline: none;
  border: none;
  font-size: 1.3rem;
  cursor: pointer;
  transition: 0.2s;
  display: flex;
  align-items: center;
  justify-content: center;
  box-shadow: 9px 9px 9px 1px rgba(92, 92, 95, 0.2);
  > svg {
    margin: 0 5px;
  }
  &:focus {
    outline: none;
  }
  ${({ theme }) => theme};
  ${is('disabled')`
    opacity: 0.5;
    cursor: not-allowed;
  `};
  ${is('inactive')`
    background-color: rgb(202, 201, 201) !important;
    color: rgb(238, 235, 235);
  `};
`

const Button = ({ theme, children, icon, ...rest }) => (
  <ButtonBase {...rest} theme={themes[theme]}>
    {icon && <i className={`fa fa-${icon}`} style={{ marginRight: 16 }} />}
    {children}
  </ButtonBase>
)

Button.propTypes = {
  theme: PropTypes.string,
  inactive: PropTypes.bool,
  icon: PropTypes.string
}

Button.defaultProps = {
  theme: 'primary',
  icon: null,
  inactive: false
}

export default Button

// client/src/components/Button.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	interface Props {
		disabled: boolean;
		class: string;
		onclick?: () => void;
		children: Snippet;
	}
	let { disabled = false, class: klass, onclick, children }: Props = $props();
</script>

<div>
	<button {disabled} class={klass} {onclick}>
		{@render children()}
	</button>
</div>

<style>
	button {
		font-size: medium;
		height: 100%;
		width: 100%;
		margin: 0 0 0.5rem 0;
		border: 0;
		padding: 0;
		border-radius: var(--radius);
		box-shadow: var(--shadow);
		color: rgba(255, 255, 255, 0.8);
		text-shadow: var(--text-raised);
		transition: all 0.2s ease;
		cursor: pointer;
	}

	button:hover:not([disabled]) {
		filter: brightness(1.1);
		box-shadow: var(--shadow-hover);
	}

	button:active:not([disabled]) {
		filter: brightness(0.95);
		box-shadow: var(--shadow-active);
	}

	button[disabled] {
		cursor: not-allowed;
		opacity: 0.8;
	}

	div {
		margin: 0;
		border: 0;
		padding: 0;
	}
</style>
